(defpackage :lispcord.classes
  (:nicknames :lc)
  (:use :cl
	:jonathan
	:lispcord.util)
  (:shadow #:type
	   #:position
	   #:inline
	   #:count
	   #:member)
  
  (:export #:%to-json
	   #:from-json

	   #:make-game
	   
	   #:overwrite
	   #:user
	   #:account
	   #:integration
	   #:emoji
	   #:channel
	   #:guild-channel
	   #:category
	   #:text-channel
	   #:voice-channel
	   #:dm-channel
	   #:group-dm
	   #:role
	   #:guild
	   #:member
	   #:embed
	   #:embed-footer
	   #:embed-image
	   #:embed-thumbnail
	   #:embed-video
	   #:embed-provider
	   #:embed-author
	   #:embed-field
	   #:game
	   #:presence
	   #:attachement
	   #:reaction
	   #:message

	   #:id
	   #:username
	   #:discrim
	   #:avatar
	   #:botp
	   #:mfa-p
	   #:verifiedp
	   #:emailp
	   #:guild-id
	   #:type
	   #:allow
	   #:deny
	   #:name
	   #:position
	   #:overwrites
	   #:parent-id
	   #:nsfw-p
	   #:topic
	   #:last-message
	   #:bitrate
	   #:user-limit
	   #:recipients
	   #:icon
	   #:owner
	   #:text
	   #:icon-proxy
	   #:url
	   #:proxy-url
	   #:height
	   #:width
	   #:value
	   #:inline
	   #:title
	   #:description
	   #:timestamp
	   #:color
	   #:footer
	   #:image
	   #:thumbnail
	   #:video
	   #:provider
	   #:author
	   #:fields
	   #:roles
	   #:user
	   #:colonsp
	   #:managedp
	   #:hoistp
	   #:permissions
	   #:mentionablep
	   #:nick
	   #:deafp
	   #:mutep
	   #:game
	   #:status
	   #:splash
	   #:region
	   #:afk-id
	   #:afk-to
	   #:embedp
	   #:embed-id
	   #:verify-level
	   #:notify-level
	   #:content-filter
	   #:emojis
	   #:features
	   #:mfa-level
	   #:app-id
	   #:widgetp
	   #:widget-id
	   #:largep
	   #:availablep
	   #:member-count
	   #:members
	   #:channels
	   #:presences
	   #:enabledp
	   #:syncingp
	   #:role-id
	   #:expire-behaviour
	   #:expire-grace
	   #:account
	   #:synced-at
	   #:filename
	   #:size
	   #:channel-id
	   #:content
	   #:editedp
	   #:tts-p
	   #:mention-all-p
	   #:mentions
	   #:mention-roles
	   #:attachements
	   #:embeds
	   #:reactions
	   #:nonce
	   #:pinnedp
	   #:webhook-id
	   #:type))
